### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/www-choo#1]
As per https://github.com/yoshuawuyts/choo/issues/201#issuecomment-236087133 here's some stuff I think that needs to happen for this site to be :sparkles: great :sparkles: This might be a bit less structured than I'd like, but hopefully it'll give people enough to go on to implement. Any help on this is more than welcome!
- create a "links" section similar to the header in the `choo` repo; providing links to other interesting pages (e.g. repo, 
- create a separate page for "awesome" - if we could emulate https://pull-stream.github.io/ that'd be amaze :v:
- animate the little train, https://twitter.com/choochoobot with parallax would be so so good
- animate the little octocat to be like this octocat: http://hughsk.io/tap-to-start/
- create an API / concepts page where we can explain how the concepts and implementation work
- perhaps move the lil graph to the concepts page
- add the philosophy section to the main page
- perhaps auto generate content based off the github readme
- create an auto-build process whenever the main `choo` repo updates to build and redeploy this repo

I think the goal of the landing page is to get people stoked about `choo`. Make them feel the philosophy, put down the slight "hey we're very much us" vibe, and provide enough grips for people to proceed where they need to go. How does that sound?

**Comment by YerkoPalma** [comment]
For the animated octocat - http://codepen.io/Rplus/pen/wKZOBo

**Comment by yoshuawuyts** [comment]
@YerkoPalma awww so cute :heart:

**Comment by yoshuawuyts** [comment]
don't think this is relevant anymore. Thanks all!
