### ISSUE TITLE
local setup

### ISSUE THREAD

**Issue by kareniel** [yoshuawuyts/www-choo#3]
Hi!

I just spend some time playing around with the repo.

The `#app-root` div doesn't exist in the DOM at the moment of appending the output of `app.start()` to the body. Which inevitably breaks the bootstrapping of the app because `document.querySelector` can't find it.

So to be able to even render anything I had to remove the argument from `app.start()`.
However, that code seems to work on the live website, so I'm not sure what to do about this.

Is there something I'm missing?

❤️ !

**Comment by yoshuawuyts** [comment]
Heya, I'm sorry I never got back to you — totally missed this. We're currently working on a redesigned website under `choojs/website`;
don't think there's much merit to keeping this issue open any longer. Thanks!
